import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";

const monaSans = Mona_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],  // Specify the weights you want
  display: 'swap',
  variable: '--font-mona-sans'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
