import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";

const inter = Mona_Sans({
  subsets: ['latin'],
  display: 'swap',     // optional
  weight: ['200', '300', '400', '500', '600', '700', '900'], // optional: choose specific weights
  variable: '--font-inter', // optional: use as a CSS variable
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
